---

- hosts: browservice
  become: yes

  tasks:
    - name: gather package facts
      package_facts:
        manager: auto

    - name: find out latest release of browservice
      uri:
        url: "{{ bs_latest }}"
        return_content: yes
      register: bs_latest_release
    
    - debug:
        var: bs_latest_release.json.tag_name

    - name: Update the system to the latest packages
      yum:
        name: "*"
        state: latest
      async: 10800
      poll: 0
      register: rhel_upgrade_status

    - name: Check on system updates
      async_status:
        jid: "{{ rhel_upgrade_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 10
      retries: 2880

    - name: install browservice locally
      import_tasks: local-service.yml
      when:
        - local_service | bool

    - name: install browservice in a container
      import_tasks: container-service.yml
      when: container_service | bool
  
    - name: open firewalld port
      firewalld:
        port: "{{ port }}/tcp"
        state: "enabled"
        immediate: yes
        permanent: yes
  
    - name: enable service
      systemd:
        name: browservice
        daemon_reload: yes
        enabled: yes
        state: started
  
    - name: restart service
      systemd:
        name: browservice
        state: restarted

...
